# Generated by Django 5.1.3 on 2024-11-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_organization_name_customer_role'),
        ('events', '0002_remove_event_season_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to='customers.customer', verbose_name='Организатор'),
        ),
    ]
