# Generated by Django 5.1.3 on 2024-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_organization_name_customer_role'),
        ('events', '0003_event_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text', models.CharField(max_length=255)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='attended_events', to='customers.customer', verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата и время начала проведения'),
        ),
        migrations.AddField(
            model_name='event',
            name='conditions',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.condition', verbose_name='Условия проведения'),
        ),
    ]
