# Generated by Django 5.1.3 on 2024-11-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_organization_name_customer_role'),
        ('events', '0004_condition_event_max_participants_event_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='added_participants', to='customers.customer', verbose_name='Участники'),
        ),
    ]
