# Generated by Django 5.1.3 on 2024-11-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
