# Generated by Django 5.1.3 on 2024-11-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_organization_name_customer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Изображение аватара пользователя', null=True, upload_to='customers/avatars', verbose_name='Аватар пользователя'),
        ),
    ]
